// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package userdb

type Account struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Enabled  bool   `json:"enabled"`
}
