// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package userdb

import (
	"context"
)

type Querier interface {
	GetAccountByID(ctx context.Context, id int64) (Account, error)
	UserLogin(ctx context.Context, arg UserLoginParams) (UserLoginRow, error)
}

var _ Querier = (*Queries)(nil)
